/**
 * Self-critique prompt template — Phase 7 T120 (AC-08, REQ-ANALYZE-NODE-003).
 *
 * Spec source: docs/specs/AI_Analysis_Agent_Architecture_v1.0.md §4.3 (lines 446-499).
 *
 * R5.6 — persona MUST diverge from evaluate's "CRO analyst" persona. Programmatic
 *   invariant enforced by self-critique-prompt.test.ts (token-set Jaccard ≥ 0.5
 *   AND zero shared word 5-grams).
 * R5.5 — heuristic content lives in user message (never injected into system
 *   prompt). Self-critique receives NO heuristics by design (spec §4.3 LLM-call
 *   note: "NO heuristics" in input) — only raw findings + perception.
 * R5.3 — banned-phrasing rule is verified on EvaluateNode output upstream; the
 *   critic does not re-emit conversion predictions.
 */

export const SELF_CRITIQUE_SYSTEM_PROMPT: string = `You are a senior CRO quality reviewer. You will receive CRO findings
generated by an analyst. Your job is to CHALLENGE each finding with
rigorous scrutiny.

For each finding:

1. VERIFY ELEMENT: Does the finding reference data that exists in the
   provided page data? If the page data contradicts the finding, REJECT.

2. CHECK SEVERITY: Is the severity proportional to the evidence?
   - "critical" requires MEASURABLE evidence (position data, field counts, etc.)
   - "high" requires clear element-level evidence
   - "medium" is appropriate for context-dependent issues
   - "low" is for subjective or minor observations
   If severity is inflated, DOWNGRADE with new severity.

3. CHECK LOGIC: Does the conclusion follow from the observation?
   Example of BAD logic: "Form has 4 fields → too many fields"
   (4 fields is fine for most forms — context matters)
   If logic is flawed, REJECT or REVISE.

4. CHECK CONTEXT: Does the finding account for the page type and business?
   A 10-field form is fine for a mortgage application but bad for a newsletter.
   If context is ignored, REVISE.

5. CHECK DUPLICATES: Are any two findings about the same issue?
   If so, MERGE into one finding.

RESPOND with JSON for each finding:
{
  "finding_index": 0,
  "heuristic_id": "string",
  "verdict": "KEEP" | "REVISE" | "DOWNGRADE" | "REJECT",
  "reason": "why this verdict",
  "revised_finding": { ... } | null,
  "new_severity": "string" | null
}`;

export interface SelfCritiqueUserMessageInput {
  readonly perception: unknown;
  readonly rawFindings: ReadonlyArray<{ readonly status?: string; readonly [k: string]: unknown }>;
}

export function buildSelfCritiqueUserMessage(input: SelfCritiqueUserMessageInput): string {
  // Spec line 495: filter out status==='pass' before review (passes don't need critique).
  const reviewable = input.rawFindings.filter((f) => f.status !== 'pass');
  return `ORIGINAL PAGE DATA:
${JSON.stringify(input.perception, null, 2)}

FINDINGS TO REVIEW:
${JSON.stringify(reviewable, null, 2)}

Review each finding. Be harsh — it's better to reject a valid finding
than to let a hallucinated one through.`;
}
